version: "3.8"

services:

    downloader:
        container_name: downloader
        build: .
        command: /app/downloader.sh
        environment:
            - |
                DOWNLOADER_LIST=
                movie https://www.youtube.com/watch?v=HJpDlGvY6YE My Note
                music https://www.youtube.com/watch?v=HJpDlGvY6YE
                musicvideo https://www.youtube.com/watch?v=HJpDlGvY6YE
                series https://www.youtube.com/watch?v=HJpDlGvY6YE
                xyz https://www.youtube.com/watch?v=HJpDlGvY6YE
            - POST_EXECUTION_COMMAND=echo "Here is post execution command."
        volumes:
            - "./data-local:/media/downloader"
